app:
  auth:
    require-email-verification: false # 기본값: 개발에 우호적

spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  web:
    resources:
      static-locations: "classpath:/static/,classpath:/public/,classpath:/resources/:"

  # OAuth2 공통 설정
  security:
    oauth2:
      client:
        registration:
          # 네이버 로그인 설정
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - email
              - nickname
              - profile_image
              - gender
              - birthyear
              - birthday
            client-name: Naver

          # 구글 로그인 설정
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile

        provider:
          # 네이버 Provider 설정
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


mybatis:
  mapper-locations: classpath:mapper/**/*.xml # Mapper.xml 구성 파일의 위치.
  configuration:
    default-statement-timeout: 30 # 디폴트 타임아웃 설정.
    map-underscore-to-camel-case: true # 데이터베이스 칼럼 이름을 언더스코어(_) → 카멜케이스로 자동 변환.
    jdbc-type-for-null: varchar # varchar 로 설장하면, NULL 값을 빈문자열(””)로 처리함.
    call-setters-on-nulls: true # true로 함으로써 db의 데이터 중 null인 값을 가져올 수 있도록 함.
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-unknown-column-behavior: none # Mybatis에서 알 수 없는 칼럼에 대한 자동 매핑 동작.
                                               #- NONE : 알 수 없는 칼럼은 무시.
                                               #- WARNING : 알 수 없는 칼럼은 무시되지 않고, 경고 메세지가 기록.
                                               #- FAILING : 예외를 던짐.

server:
  port: 8080
  jsp-servlet:
    init-parameters:
      development: false