logging:
  level:
    root: INFO                # 최소 WARN 이상이어야 log.warn() 표시
    com.ssr.newskuku: DEBUG

spring:
  # ===================================================================
  # 1. 데이터소스(DB) 설정
  # H2 데이터베이스에 어떻게 연결할지 스프링에게 알려줍니다.
  # ===================================================================
  datasource:
    # url: jdbc:h2:mem:solidtask -> 'solidtask'라는 이름의 메모리 기반 DB를 사용합니다.
    # 서버를 재시작하면 데이터는 사라집니다.
    url: jdbc:h2:mem:testdb;;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    username: sa # H2 DB 기본 사용자 이름
    password: # 비밀번호는 없음
    driver-class-name: org.h2.Driver # H2 드라이버 지정

  # ===================================================================
  # 2. H2 데이터베이스 콘솔 설정
  # 개발 중 DB 테이블과 데이터를 눈으로 직접 볼 수 있게 해주는 웹 콘솔 기능입니다.
  # ===================================================================
  h2:
    console:
      enabled: true # H2 콘솔 기능 활성화
      path: /h2-console # 브라우저에서 접속할 경로 http://localhost:8080/h2-console

  sql:
    init:
      mode: always       # 서버 실행 시 SQL 파일 실행
      data-locations: classpath:db/data.sql

notification:
  policy:
    # 이슈 상태가 DONE 으로 변경되었을 때 사용할 알림 타입 지정
    on-status-done: PUSH

openai:
  api-key: "test-api-key-for-development"
  api-url: https://api.openai.com/v1/chat/completions
  model: gpt-5-nano