app:
  auth:
    require-email-verification: false # 기본값: 개발에 우호적

spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  web:
    resources:
      static-locations: "classpath:/static/,classpath:/public/,classpath:/resources/:"

mybatis:
  mapper-locations: classpath:mapper/**/*.xml # Mapper.xml 구성 파일의 위치.
  configuration:
    default-statement-timeout: 30 # 디폴트 타임아웃 설정.
    map-underscore-to-camel-case: true # 데이터베이스 칼럼 이름을 언더스코어(_) → 카멜케이스로 자동 변환.
    jdbc-type-for-null: varchar # varchar 로 설장하면, NULL 값을 빈문자열(””)로 처리함.
    call-setters-on-nulls: true # true로 함으로써 db의 데이터 중 null인 값을 가져올 수 있도록 함.
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-unknown-column-behavior: none # Mybatis에서 알 수 없는 칼럼에 대한 자동 매핑 동작.
                                               #- NONE : 알 수 없는 칼럼은 무시.
                                               #- WARNING : 알 수 없는 칼럼은 무시되지 않고, 경고 메세지가 기록.
                                               #- FAILING : 예외를 던짐.

server:
  port: 8080
  jsp-servlet:
    init-parameters:
      development: false

openai:
  api-key: ${OPENAI_API_KEY} # 실제 OpenAi 대시보드에서 발급받은 API KEY 입력
  api-url: https://api.openai.com/v1/chat/completions # GPT 대화용 API URL
  model: gpt-5-nano # 사용할 모델