logging:
  level:
    root: INFO                # 최소 WARN 이상이어야 log.warn() 표시
    com.ssr.newskuku: DEBUG

spring:
  # ===================================================================
  # 1. 데이터소스(DB) 설정
  # H2 데이터베이스에 어떻게 연결할지 스프링에게 알려줍니다.
  # ===================================================================
  datasource:
    url: jdbc:mysql://192.168.0.84/newskuku?useSSl=false&serverTimezone=Asia/Seoul
    username: newskuku_admin
    password: ghkdlxld1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true # H2 콘솔 기능 활성화
      path: /h2-console # 브라우저에서 접속할 경로 http://localhost:8080/h2-console

#  sql:
#    init:
#      mode: always       # 서버 실행 시 SQL 파일 실행
#      data-locations: classpath:db/data.sql

notification:
  policy:
    # 이슈 상태가 DONE 으로 변경되었을 때 사용할 알림 타입 지정
    on-status-done: PUSH

openai:
  api-key: "test-api-key-for-development"
  api-url: https://api.openai.com/v1/chat/completions
  model: gpt-5-nano